### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by barnett2010** [HearthSim/python-fsb5#15]
python extract.py -o a 8013_1.fsb

Traceback (most recent call last):
  File "extract.py", line 131, in <module>
    main()
  File "extract.py", line 127, in main
    exit(app.run(sys.argv[1:]))
  File "extract.py", line 121, in run
    self.handle_file(f)
  File "extract.py", line 110, in handle_file
    for sample_fakepath, sample_name, sample_data in self.read_samples(fakepath_prefix, fsb, ext):
  File "extract.py", line 86, in read_samples
    yield sample_fakepath, sample.name, fsb.rebuild_sample(sample)
  File "C:\1\fsb5jb\fsb5\__init__.py", line 211, in rebuild_sample
    from . import vorbis
  File "C:\1\fsb5jb\fsb5\vorbis.py", line 12, in <module>
    vorbis = load_lib('vorbis')
  File "C:\1\fsb5jb\fsb5\utils.py", line 76, in load_lib
    raise LibraryNotFoundException("Could not load the library %r" % (names[0]))
fsb5.utils.LibraryNotFoundException: Could not load the library 'vorbis'

**Comment by AKAAkira** [comment]
From the README:

> libogg and libvorbis are required to decode ogg samples. For linux simply install from your package manager. For windows ensure the dlls are avaliable (ie. in System32 or the directory you are running the script from). Known working dlls are avaliable as part of the release.

Whether you downloaded the Win64 or Win32 version (and not the source code zip named `python-fsb5-b7bf605`), you should've obtained `libvorbis.dll` and `libogg.dll`. Just have them in the folder you're running `extract.py` from. Or, rename them `vorbis.dll` and `ogg.dll` and move them to C:\Windows\System32 (assuming you're running Windows).

**Comment by AlphaTwentyThree** [comment]
Similar thing on my end:

```C:\!temp>python extract.py "Master Bank.fsb"
Traceback (most recent call last):
  File "C:\!temp\extract.py", line 131, in <module>
    main()
  File "C:\!temp\extract.py", line 127, in main
    exit(app.run(sys.argv[1:]))
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\!temp\extract.py", line 121, in run
    self.handle_file(f)
  File "C:\!temp\extract.py", line 110, in handle_file
    for sample_fakepath, sample_name, sample_data in self.read_samples(fakepath_prefix, fsb, ext):
  File "C:\!temp\extract.py", line 86, in read_samples
    yield sample_fakepath, sample.name, fsb.rebuild_sample(sample)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\!temp\fsb5\__init__.py", line 211, in rebuild_sample
    from . import vorbis
  File "C:\!temp\fsb5\vorbis.py", line 12, in <module>
    vorbis = load_lib('vorbis')
             ^^^^^^^^^^^^^^^^^^
  File "C:\!temp\fsb5\utils.py", line 76, in load_lib
    raise LibraryNotFoundException("Could not load the library %r" % (names[0]))
fsb5.utils.LibraryNotFoundException: Could not load the library 'vorbis'
```

Registering the provided DLLs, placing them into System32 or SysWOW64, nothing works:
![image](https://github.com/HearthSim/python-fsb5/assets/97170745/3415b2a9-4a60-4cf9-af07-6a1a63fbc718)

**Comment by 0zhangsan0** [comment]
you need to move libogg.dll and libvorbis.dll to the folder where extract.py is located.

**Comment by AlphaTwentyThree** [comment]
> you need to move libogg.dll and libvorbis.dll to the folder where extract.py is located.

Aaah, gotcha. Thanks. Somehow this isn't noticeable enough in the documentation. That said, I've stopped doing data mining, but at least others now know how to fix the issue.
